version: '3.8'

services:
  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - '8807:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lms_radec
      MYSQL_USER: lms_radec
      MYSQL_PASSWORD: lms_radec
    networks:
      - lms-radec-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    links: 
      - mysql
    ports:
      - '8087:80'
    depends_on: 
      - mysql
    environment:
      - PMA_HOST=mysql
      - PMA_USER=lms_radec
      - PMA_PASSWORD=lms_radec
    networks:
      - lms-radec-network

networks:
  lms-radec-network:
